// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPE5dNP_m703QNkPbH-UovwW50s2eAWts',
    appId: '1:341304961285:web:ce793ff19589d80ab0af6c',
    messagingSenderId: '341304961285',
    projectId: 'community-service-b06ac',
    authDomain: 'community-service-b06ac.firebaseapp.com',
    databaseURL: 'https://community-service-b06ac-default-rtdb.firebaseio.com',
    storageBucket: 'community-service-b06ac.appspot.com',
    measurementId: 'G-L4MNH35YW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNlbvEjUpxlQ7c6adjc-TYpjLjdwKGVM',
    appId: '1:341304961285:android:6b2484c7be7afbbab0af6c',
    messagingSenderId: '341304961285',
    projectId: 'community-service-b06ac',
    databaseURL: 'https://community-service-b06ac-default-rtdb.firebaseio.com',
    storageBucket: 'community-service-b06ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOSblUlXVAuuH3oSe4UYclzwu0LtwN-fE',
    appId: '1:341304961285:ios:7fed7fcc0d8e6df3b0af6c',
    messagingSenderId: '341304961285',
    projectId: 'community-service-b06ac',
    databaseURL: 'https://community-service-b06ac-default-rtdb.firebaseio.com',
    storageBucket: 'community-service-b06ac.appspot.com',
    iosBundleId: 'com.example.communityService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOSblUlXVAuuH3oSe4UYclzwu0LtwN-fE',
    appId: '1:341304961285:ios:955f04c92101c504b0af6c',
    messagingSenderId: '341304961285',
    projectId: 'community-service-b06ac',
    databaseURL: 'https://community-service-b06ac-default-rtdb.firebaseio.com',
    storageBucket: 'community-service-b06ac.appspot.com',
    iosBundleId: 'com.example.communityService.RunnerTests',
  );
}
